"""add_production_year_field

Revision ID: 063711312faf
Revises: ca0c2cf9ad15
Create Date: 2026-10-01 08:22:09.529709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063711312faf'
down_revision: Union[str, Sequence[str], None] = 'ca0c2cf9ad15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('production_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'production_year')
    # ### end Alembic commands ###
